### ISSUE TITLE
Improper removal of recipes

### ISSUE THREAD

**Issue by player19375** [ThePoleThatFishes/NC-Extra-Ingot-Blocks#4]
The recipes of CoT platinum block (and other blocks too) are still present despite the fact that they are removed from JEI.
<img width="432" alt="Screenshot 2021-10-04 at 11 29 03" src="https://user-images.githubusercontent.com/83454653/135789746-b2737df2-8150-40bc-b038-bce754a4d2c8.png">

**Comment by ThePoleThatFishes** [comment]
Since there hasn't been an update on this bug after deploying the fix, I'm closing this as resolved.
